feat: complete the live update and file creation processes

diff --git a/.github/workflows/update_alerts_with_results.yml b/.github/workflows/update_alerts_with_results.yml
--- a/.github/workflows/update_alerts_with_results.yml
+++ b/.github/workflows/update_alerts_with_results.yml
@@ -14,6 +14,7 @@ jobs:
     env:
       TZ: Africa/Lagos
       RESULT_LOG_FILE: remote_results.csv
+      FINAL_DB_FILE: remote_final_db.csv
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -64,12 +65,12 @@ jobs:
         run: |
           git config --global user.name "GitHub Actions Bot"
           git config --global user.email "actions@github.com"
-          if [ -f "$RESULT_LOG_FILE" ]; then
-            git add -f "$RESULT_LOG_FILE"
-            git commit -m "chore: pull results data from the previous day [Run ${{ github.run_number }}]" || true
+          if [ -f "$FINAL_DB_FILE" ]; then
+            git add -f "$FINAL_DB_FILE"
+            git commit -m "chore: update final db file with results data from the previous day [Run ${{ github.run_number }}]" || true
             git push origin main
           else
-            echo "⚠️ $RESULT_LOG_FILE not found, skipping commit"
+            echo "⚠️ $FINAL_DB_FILE not found, skipping commit"
           fi
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
